-- prints full description of table

SELECT CONCAT(
	'CREATE TABLE `',
	TABLE_NAME,
	'` (\n',
	GROUP_CONCAT(
		CONCAT('  `', COLUMN_NAME, '` ', COLUMN_TYPE,
			IF(IS_NULLABLE = 'NO', ' NOT NULL', ''),
			IF(COLUMN_KEY = 'PRI', ' PRIMARY KEY', ''),
			IF(EXTRA = 'auto_increment', ' AUTO_INCREMENT', ''),
			IF(COLUMN_DEFAULT IS NOT NULL, CONCAT(' DEFAULT ', COLUMN_DEFAULT), ''),
			',\n
		) ORDER BY ORDINAL_POSITION SEPARATOR ''
	),
	') ENGINE=', ENGINE,
	' DEFAULT CHARSET=', CHARACTER_SET_NAME,
	' COLLATE=', COLLATION_NAME
) AS TableDescription
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'first_table'
GROUP BY TABLE_NAME, ENGINE, CHARACTER_SET_NAME, COLLATION_NAME;
